import React from 'react';
import {View, Button, PermissionsAndroid, Text} from 'react-native';
import SmsAndroid from 'react-native-get-sms-android';
import PushNotification from 'react-native-push-notification';

const App = () => {
  const sendsms = async () => {
    try {
      let granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.SEND_SMS,
        {
          title: 'Send SMS',
          message: 'Need access to send sms',
        },
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('SEND_SMS permissions granted', granted);
        SmsAndroid.autoSend(
          '+8801764225218',
          'This is a direct message',
          (fail) => {
            console.log('Failed with this error: ' + fail);
          },
          (success) => {
            console.log('SMS sent successfully');
          },
        );
      } else {
        Alert.alert('SEND_SMS permissions denied');
        console.log('SEND_SMS permissions denied');
      }
    } catch (err) {
      Alert.alert(err);
    }
  };
  const notification = () => {
    PushNotification.localNotificationSchedule({
      /* Android Only Properties */
      id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
      subText: 'This is a subText', // (optional) default: none
      color: 'red', // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      priority: 'high', // (optional) set notification priority, default: high
      visibility: 'private', // (optional) set notification visibility, default: private
      importance: 'high', // (optional) set notification importance, default: high
      allowWhileIdle: false, // (optional) set notification to work while on doze, default: false
      ignoreInForeground: false, // (optional) if true, the notification will not be visible when the app is in the foreground (useful for parity with how iOS notifications appear)

      /* iOS only properties */
      alertAction: 'view', // (optional) default: view
      category: '', // (optional) default: empty string
      userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)

      /* iOS and Android properties */
      title: 'My Notification Title', // (optional)
      message: 'My Notification Message', // (required)
      date: new Date(Date.now() + 10 * 1000),
      playSound: true, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      repeatType: 'time', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
      repeatTime: 10000,
      actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
    });
  };
  return (
    <View
      style={{justifyContent: 'center', alignSelf: 'center', marginTop: 100}}>
      <Text>Push Notification Will come in every 10 second after clicking</Text>
      <View style={{marginBottom: 100}}>
        <Button title="Send Notification" onPress={notification}></Button>
      </View>
      <Button
        title="Send SMS"
        onPress={sendsms}
        style={{margin: 100}}
        color="black"></Button>
    </View>
  );
};

export default App;
